spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/piepay?useSSL=false&useUnicode=true
    username: root
    password: ssafy

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ba6cf73aabce34cf56a4ea69828ad3bb
            client-secret: g35E1lym7qKG6DBNwPoYa3xT5fVh49kc
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
  data:
    redis:
      port: 6379
      host: localhost

jwt:
  issuer: pie
  key:
    salt: Uv38ByGCZU8WP18PmmIdcpVmx00QA3xNe7sEB9Hixkk=
  expire_time:
    access-token: 9000000000000
    refresh-token: 3600000000000000
coolSms:
  api-key: NCSTKQSOYGNPAIXR
  api-secret-key: 12ES6GJPZQSI90DMRVRPDQQ6KNBLKOQT

bank:
  api-key: 56fef2f913d04ae79b1d44d7e96ccec3
  url:
    create-account: https://finapi.p.ssafy.io/ssafy/api/v1/member
    search-account: https://finapi.p.ssafy.io/ssafy/api/v1/member/search